---
abstract: 'a distribution of modules to handle locale codes'
author:
  - 'Sullivan Beck (sbeck@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Inter: '1.09'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locale-Codes
no_index:
  directory:
    - t
    - inc
provides:
  Locale::Codes:
    file: lib/Locale/Codes.pm
    version: '3.63'
  Locale::Codes::Constants:
    file: lib/Locale/Codes/Constants.pm
    version: '3.63'
  Locale::Codes::Country:
    file: lib/Locale/Codes/Country.pm
    version: '3.63'
  Locale::Codes::Country_Codes:
    file: lib/Locale/Codes/Country_Codes.pm
    version: '3.63'
  Locale::Codes::Country_Retired:
    file: lib/Locale/Codes/Country_Retired.pm
    version: '3.63'
  Locale::Codes::Currency:
    file: lib/Locale/Codes/Currency.pm
    version: '3.63'
  Locale::Codes::Currency_Codes:
    file: lib/Locale/Codes/Currency_Codes.pm
    version: '3.63'
  Locale::Codes::Currency_Retired:
    file: lib/Locale/Codes/Currency_Retired.pm
    version: '3.63'
  Locale::Codes::LangExt:
    file: lib/Locale/Codes/LangExt.pm
    version: '3.63'
  Locale::Codes::LangExt_Codes:
    file: lib/Locale/Codes/LangExt_Codes.pm
    version: '3.63'
  Locale::Codes::LangExt_Retired:
    file: lib/Locale/Codes/LangExt_Retired.pm
    version: '3.63'
  Locale::Codes::LangFam:
    file: lib/Locale/Codes/LangFam.pm
    version: '3.63'
  Locale::Codes::LangFam_Codes:
    file: lib/Locale/Codes/LangFam_Codes.pm
    version: '3.63'
  Locale::Codes::LangFam_Retired:
    file: lib/Locale/Codes/LangFam_Retired.pm
    version: '3.63'
  Locale::Codes::LangVar:
    file: lib/Locale/Codes/LangVar.pm
    version: '3.63'
  Locale::Codes::LangVar_Codes:
    file: lib/Locale/Codes/LangVar_Codes.pm
    version: '3.63'
  Locale::Codes::LangVar_Retired:
    file: lib/Locale/Codes/LangVar_Retired.pm
    version: '3.63'
  Locale::Codes::Language:
    file: lib/Locale/Codes/Language.pm
    version: '3.63'
  Locale::Codes::Language_Codes:
    file: lib/Locale/Codes/Language_Codes.pm
    version: '3.63'
  Locale::Codes::Language_Retired:
    file: lib/Locale/Codes/Language_Retired.pm
    version: '3.63'
  Locale::Codes::Script:
    file: lib/Locale/Codes/Script.pm
    version: '3.63'
  Locale::Codes::Script_Codes:
    file: lib/Locale/Codes/Script_Codes.pm
    version: '3.63'
  Locale::Codes::Script_Retired:
    file: lib/Locale/Codes/Script_Retired.pm
    version: '3.63'
  Locale::Country:
    file: lib/Locale/Country.pm
    version: '3.63'
  Locale::Currency:
    file: lib/Locale/Currency.pm
    version: '3.63'
  Locale::Language:
    file: lib/Locale/Language.pm
    version: '3.63'
  Locale::Script:
    file: lib/Locale/Script.pm
    version: '3.63'
requires:
  Carp: '0'
  if: '0'
  perl: '5.006'
  utf8: '0'
resources:
  repository: git://github.com/SBECK-github/Locale-Codes.git
version: '3.63'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
