---
abstract: 'a distribution of modules to handle locale codes'
author:
  - 'Sullivan Beck (sbeck@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
  Storable: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locale-Codes
no_index:
  directory:
    - t
    - inc
provides:
  Locale::Codes:
    file: Codes.pm
    version: '3.54'
  Locale::Codes::Constants:
    file: Constants.pm
    version: '3.54'
  Locale::Codes::Country:
    file: Country.pm
    version: '3.54'
  Locale::Codes::Country_Codes:
    file: Country_Codes.pm
    version: '3.54'
  Locale::Codes::Country_Retired:
    file: Country_Retired.pm
    version: '3.54'
  Locale::Codes::Currency:
    file: Currency.pm
    version: '3.54'
  Locale::Codes::Currency_Codes:
    file: Currency_Codes.pm
    version: '3.54'
  Locale::Codes::Currency_Retired:
    file: Currency_Retired.pm
    version: '3.54'
  Locale::Codes::LangExt:
    file: LangExt.pm
    version: '3.54'
  Locale::Codes::LangExt_Codes:
    file: LangExt_Codes.pm
    version: '3.54'
  Locale::Codes::LangExt_Retired:
    file: LangExt_Retired.pm
    version: '3.54'
  Locale::Codes::LangFam:
    file: LangFam.pm
    version: '3.54'
  Locale::Codes::LangFam_Codes:
    file: LangFam_Codes.pm
    version: '3.54'
  Locale::Codes::LangFam_Retired:
    file: LangFam_Retired.pm
    version: '3.54'
  Locale::Codes::LangVar:
    file: LangVar.pm
    version: '3.54'
  Locale::Codes::LangVar_Codes:
    file: LangVar_Codes.pm
    version: '3.54'
  Locale::Codes::LangVar_Retired:
    file: LangVar_Retired.pm
    version: '3.54'
  Locale::Codes::Language:
    file: Language.pm
    version: '3.54'
  Locale::Codes::Language_Codes:
    file: Language_Codes.pm
    version: '3.54'
  Locale::Codes::Language_Retired:
    file: Language_Retired.pm
    version: '3.54'
  Locale::Codes::Script:
    file: Script.pm
    version: '3.54'
  Locale::Codes::Script_Codes:
    file: Script_Codes.pm
    version: '3.54'
  Locale::Codes::Script_Retired:
    file: Script_Retired.pm
    version: '3.54'
  Locale::Country:
    file: Country.pm
    version: '3.54'
  Locale::Currency:
    file: Currency.pm
    version: '3.54'
  Locale::Language:
    file: Language.pm
    version: '3.54'
  Locale::Script:
    file: Script.pm
    version: '3.54'
requires:
  Carp: '0'
  perl: '5.006'
  utf8: '0'
resources:
  repository: git://github.com/SBECK-github/Locale-Codes.git
version: '3.54'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
