---
abstract: 'a distribution of modules to handle locale codes'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
build_requires:
  Module::Build: '0.21'
  Storable: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.21'
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locale-Codes
provides:
  Locale::Codes:
    file: lib/Locale/Codes.pm
    version: '3.34'
  Locale::Codes::Constants:
    file: lib/Locale/Codes/Constants.pm
    version: '3.34'
  Locale::Codes::Country:
    file: lib/Locale/Codes/Country.pm
    version: '3.34'
  Locale::Codes::Currency:
    file: lib/Locale/Codes/Currency.pm
    version: '3.34'
  Locale::Codes::LangExt:
    file: lib/Locale/Codes/LangExt.pm
    version: '3.34'
  Locale::Codes::LangFam:
    file: lib/Locale/Codes/LangFam.pm
    version: '3.34'
  Locale::Codes::LangVar:
    file: lib/Locale/Codes/LangVar.pm
    version: '3.34'
  Locale::Codes::Language:
    file: lib/Locale/Codes/Language.pm
    version: '3.34'
  Locale::Codes::Script:
    file: lib/Locale/Codes/Script.pm
    version: '3.34'
  Locale::Country:
    file: lib/Locale/Country.pm
    version: '3.34'
  Locale::Currency:
    file: lib/Locale/Currency.pm
    version: '3.34'
  Locale::Language:
    file: lib/Locale/Language.pm
    version: '3.34'
  Locale::Script:
    file: lib/Locale/Script.pm
    version: '3.34'
requires:
  Carp: '0'
  perl: '5.006'
  utf8: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/SBECK-github/Locale-Codes
version: '3.34'
