perl -I../lib alias_code.t 1
perl -I../lib alias_code_old.t 1
perl -I../lib code2country.t 1
perl -I../lib code2country_old.t 1
perl -I../lib code2currency.t 1
perl -I../lib code2langext.t 1
perl -I../lib code2langfam.t 1
perl -I../lib code2language.t 1
perl -I../lib code2langvar.t 1
perl -I../lib code2script.t 1
perl -I../lib country.t 1
perl -I../lib country2code.t 1
perl -I../lib country2code_old.t 1
perl -I../lib country_code2code.t 1
perl -I../lib country_code2code_old.t 1
perl -I../lib country_old.t 1
perl -I../lib currency2code.t 1
perl -I../lib currency2code_old.t 1
perl -I../lib langext2code.t 1
perl -I../lib langfam2code.t 1
perl -I../lib language.t 1
perl -I../lib language2code.t 1
perl -I../lib language_old.t 1
perl -I../lib langvar2code.t 1
perl -I../lib script2code.t 1
perl -I../lib script2code_old.t 1
