perl -I../lib country.t 1
perl -I../lib country_old.t 1
perl -I../lib currency.t 1
perl -I../lib currency_old.t 1
perl -I../lib langext.t 1
perl -I../lib langfam.t 1
perl -I../lib language.t 1
perl -I../lib language_old.t 1
perl -I../lib langvar.t 1
perl -I../lib script.t 1
perl -I../lib script_old.t 1
